// Mapped from backend
const CODES = {
  DeviceNotConfirmed: 'DEVICE_NOT_CONFIRMED',
  PhoneNumberNotConfirmed: 'PHONE_NOT_CONFIRMED',
  EmailNotConfirmed: 'EMAIL_NOT_CONFIRMED',
  AccountLocked: 'ACCOUNT_LOCKED',
  IncorrectCreds: 'INCORRECT_CREDENTIALS',
  UserDoseNotExist: 'USER_DOES_NOT_EXIST',
  VALID_EMAIL_CONFIRMATION_EXISTS: 'VALID_EMAIL_CONFIRMATION_EXISTS',
  EMAIL_ALREADY_CONFIRMED: 'EMAIL_ALREADY_CONFIRMED',
  USER_DOES_NOT_EXIST: 'USER_DOES_NOT_EXIST',
  EMAIL_CONFIRMATION: 'EMAIL_CONFIRMATION',
  PHONE_NUMBER_ALREADY_CONFIRMED: 'PHONE_NUMBER_ALREADY_CONFIRMED',
  VALID_PHONE_CONFIRMATION_EXISTS: 'VALID_PHONE_CONFIRMATION_EXISTS',
  DEVICE_NOT_CONFIRMED: 'DEVICE_NOT_CONFIRMED',
  PHONE_NUMBER_CONFIRMATION_DOES_NOT_EXIST:
    'PHONE_NUMBER_CONFIRMATION_DOES_NOT_EXIST',
  DEVICE_ALREADY_TRUSTED: 'DEVICE_ALREADY_TRUSTED',
  VALID_DEVICE_CONFIRMATION_EXISTS: 'VALID_DEVICE_CONFIRMATION_EXISTS',
  DEVICE_CONFIRMATION_DOES_NOT_EXIST: 'DEVICE_CONFIRMATION_DOES_NOT_EXIST',
  LOGIN_ATTEMPT_NOT_VALID: 'LOGIN_ATTEMPT_NOT_VALID',
  PHONE_NOT_CONFIRMED: 'PHONE_NOT_CONFIRMED',
  VALID_TWO_FACTOR_SMS_ATTEMPT_EXISTS: 'VALID_TWO_FACTOR_SMS_ATTEMPT_EXISTS',
  TWO_FACTOR_SMS_ATTEMPT_INVALID: 'TWO_FACTOR_SMS_ATTEMPT_INVALID',
  REQUIRES_PASSWORD_CHANGE: 'REQUIRES_PASSWORD_CHANGE',
  EXPIRED_PASSWORD_BEING_USED: 'EXPIRED_PASSWORD_BEING_USED',
  INCIDENT_TYPE_ALREADY_EXISTS: 'INCIDENT_TYPE_ALREADY_EXISTS',
  CASE_NUMBER_TAKEN: "CASE_NUMBER_TAKEN",
  CASE_PERMISSION: "CASE_PERMISSION"
} as const;

export default CODES;
