// Mapped from backend
const CODES = {
  DeviceNotConfirmed: 'DEVICE_NOT_CONFIRMED',
  PhoneNumberNotConfirmed: 'PHONE_NOT_CONFIRMED',
  EmailNotConfirmed: 'EMAIL_NOT_CONFIRMED',
  AccountLocked: 'ACCOUNT_LOCKED',
  IncorrectCreds: 'INCORRECT_CREDENTIALS',
  UserDoseNotExist: 'USER_DOES_NOT_EXIST',
  VALID_EMAIL_CONFIRMATION_EXISTS: 'VALID_EMAIL_CONFIRMATION_EXISTS',
  EMAIL_ALREADY_CONFIRMED: 'EMAIL_ALREADY_CONFIRMED',
  USER_DOES_NOT_EXIST: "USER_DOES_NOT_EXIST",
  EMAIL_CONFIRMATION: "EMAIL_CONFIRMATION",
  PHONE_NUMBER_ALREADY_CONFIRMED: "PHONE_NUMBER_ALREADY_CONFIRMED",
  VALID_PHONE_CONFIRMATION_EXISTS: "VALID_PHONE_CONFIRMATION_EXISTS"
} as const;

export default CODES;
