services:
  broker:
    image: rabbitmq:3-management
    container_name: message_broker
    ports:
      - "5672:5672" # AMQP protocol
      - "15672:15672" # Web management UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: StrongPassword!

  cases_cache:
    image: redis:7.2
    container_name: cases_cache
    command: ["redis-server", "--requirepass", "mysecretpassword"]
    ports:
      - "6380:6379"

  identity_cache:
    image: redis:7.2
    container_name: identity_cache
    command: ["redis-server", "--requirepass", "mysecretpassword"]
    ports:
      - "6381:6379"
