// <auto-generated />
using System;
using Cases.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cases.Infrastructure.Migrations
{
    [DbContext(typeof(CasesApplicationDbContext))]
    partial class CasesApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("Cases.Core.Models.Case", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IncidentDateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReportedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportingOfficerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CaseNumber")
                        .IsUnique();

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ReportingOfficerId");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("Cases.Core.Models.IncidentType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("IncidentTypes");
                });

            modelBuilder.Entity("Cases.Core.Models.Joins.CaseIncidentType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CaseId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IncidentTypeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("IncidentTypeId");

                    b.ToTable("CaseIncidentTypes");
                });

            modelBuilder.Entity("Cases.Core.Models.Joins.CaseIncidentType", b =>
                {
                    b.HasOne("Cases.Core.Models.Case", "Case")
                        .WithMany("CaseIncidentType")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cases.Core.Models.IncidentType", "IncidentType")
                        .WithMany("CaseIncidentType")
                        .HasForeignKey("IncidentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("IncidentType");
                });

            modelBuilder.Entity("Cases.Core.Models.Case", b =>
                {
                    b.Navigation("CaseIncidentType");
                });

            modelBuilder.Entity("Cases.Core.Models.IncidentType", b =>
                {
                    b.Navigation("CaseIncidentType");
                });
#pragma warning restore 612, 618
        }
    }
}
