using System.Security.Cryptography;
using System.Text;
using UAParser;

namespace Identity.API.Helpers
{
    public class DeviceIdentificationHelper(ILogger<DeviceIdentificationHelper> logger, Parser userAgentParser) : IDeviceIdentificationService
    {
        private readonly ILogger<DeviceIdentificationHelper> _logger = logger;
        private readonly Parser _userAgentParser = userAgentParser ?? Parser.GetDefault();

        /// <summary>
        /// Generates a unique device identifier based on user and device information.
        /// </summary>
        /// <param name="userId">The unique identifier of the user who has provided valid credentials. Must not be null or empty.</param>
        /// <param name="userAgent">The user agent string containing device and browser information. Must not be null or empty.</param>
        /// <returns>A unique hash string representing the device, combining user ID and client information.</returns>
        /// <exception cref="ArgumentException">Thrown when either userId or userAgent is null, empty, or consists only of white-space characters.</exception>
        /// <remarks>
        /// The device ID is generated by combining and hashing the following components:
        /// - User Agent family
        /// - User Agent major version
        /// - Operating System family
        /// - Operating System major version
        /// - Device family
        /// - User ID
        /// </remarks>
        public string GenerateDeviceId(string userId, string userAgent)
        {
            if(string.IsNullOrWhiteSpace(userId))
                throw new ArgumentException("User ID cannot be null or empty.", nameof(userId));

            if (string.IsNullOrWhiteSpace(userAgent))
                throw new ArgumentException("User agent cannot be null or empty.", nameof(userAgent));

            try
            {
                // Parse the user agent
                var clientInfo = _userAgentParser.Parse(userAgent);

                // Create components for device ID
                var components = new[]
                {
                    clientInfo.UA.Family,
                    clientInfo.UA.Major,
                    clientInfo.OS.Family,
                    clientInfo.OS.Major,
                    clientInfo.Device.Family,
                    userId
                };

                // Join components and create a hash
                var deviceIdSource = string.Join("-", components);
                var deviceId = ComputeDeviceIdHash(deviceIdSource);

                _logger.LogInformation(
                    "Generated Device ID for UA: {UserAgent}, ID: {userId}, Device: {DeviceFamily}",
                    clientInfo.UA.Family,
                    userId,
                    clientInfo.Device.Family);

                return deviceId;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error generating device ID for UA: {UserAgent}", userAgent);
                throw;
            }
        }

        private static string ComputeDeviceIdHash(string input)
        {
            var inputBytes = Encoding.UTF8.GetBytes(input);
            var hashBytes = SHA256.HashData(inputBytes);
            return Convert.ToBase64String(hashBytes)
                .Replace("+", "")  // Remove special characters
                .Replace("/", "")
                .Replace("=", "")
                    [..32];  // Truncate to a fixed length
        }
    }
}
