version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"       # AMQP protocol
      - "15672:15672"     # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: user  # Default username
      RABBITMQ_DEFAULT_PASS: password  # Default password
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - broker-net

networks:
  broker-net:
    driver: bridge

volumes:
  rabbitmq-data:
    driver: local
